### ISSUE TITLE
Strange result diffing hash-maps with nil value

### ISSUE THREAD

**Issue by jiyinyiyong** [Skinney/differ#15]
```clojure
[org.clojure/clojurescript "1.7.228"]
[differ "0.2.1"]
```

My values:

```clojure
{:a 1   :b 2     :c nil   :d 1     :e nil}
{:a 2   :b "x"   :c nil   :d nil   :e 2}
```

To diff them:

```clojure
cljs.user=> (require '[differ.core :as differ])
nil
cljs.user=> (differ/diff {:a 1 :b 2 :c nil :d 1 :e nil} {:a 2 :b "x" :c nil :d nil :e 2})
[{:a 2, :b "x", :c nil, :d nil, :e 2} {}]
```

Field `:c` is changed from `nil` to `nil`. This is not supposed to be here.

Actually I think the result should be like this:

```clojure
[{:a 2, :b "x", :d nil, :e 2}]
```

**Comment by Skinney** [comment]
Just release 0.2.2 which should fix this. Try it out and let me know.

**Comment by jiyinyiyong** [comment]
The `nil` issue is ok now.

Still strange too me actually:

```clj
cljs.user=> (differ/diff {:a 1} {:a 0 :b 0})
[{:a 0, :b 0} {}] ; -> not ``
```
cljs.user=> (differ/diff {:a 1 :b 1} {:a 0})
[{:a 0} {:b 0}]
cljs.user=> (differ/diff {:a nil :b 1} {:a nil})
[{} {:b 0}]
cljs.user=> (differ/diff {:a nil :b 1} {:a nil})
```

**Comment by Skinney** [comment]
What's wrong? It's `[altertions removals]`
Removals always have a value of 0 in the value position in maps. No need to duplicate values.

**Comment by jiyinyiyong** [comment]
My mistake. Thanks for the explanation.
