### ISSUE TITLE
Vector patch fails with NullPointerException

### ISSUE THREAD

**Issue by JvJ** [Skinney/differ#19]
When I run the following, it fails:

(patch [1 2 3] (diff [1 2 3] [1 2 3 4])) ;; => Null Pointer Exception, no trace

However, it succeeds as long as the top-level structure is a map:

(patch {:a [1 2 3]} (diff {:a [1 2 3]} {:a [1 2 3 4]}))  ;; => {:a [1 2 3 4]}

**Comment by Skinney** [comment]
Did you mean `(patch [1 2] [3])` ?
`(patch 1 2 3)` should fail (wrong arity) and `(patch 1 2)` should always return 2.

**Comment by Skinney** [comment]
`(patch  1 2 3)` is not valid use of the function.

`patch` takes the structure to patch, and a vector containing alterations and removals.

**Comment by Skinney** [comment]
I assume you meant `(patch [1 2 3] (diff [1 2 3] [1 2 3 4]))` which does trigger a NPE.

**Comment by kawheele** [comment]
Yeah, that's what I meant.  I think the bbcode messed me up.
